Repository woowa-techcamp-2020/market-9-blair-dnacu, pull requests merged in 2020-07, with the labels that each got.

#9 [markup] mainPage, signupPage, signupFisnishPage
  app.js
  index.html
  package-lock.json
  package.json
  styles/components.css
  styles/main.css
  styles/reset.css
  styles/signIn.css
  styles/signUp.css
  styles/signUpComplete.css
  views/main.pug
  views/signIn.pug
  views/signUp.pug
  views/signUpComplete.pug
Labels: enhancement, front

#16 Pug mixin 테스트 - 페어 프로그래밍
  app.js
  components/input/input.css
  components/input/input.pug
  pages/main/main.css
  pages/signIn/signIn.css
  pages/signUp/signUp.css
  pages/signUp/signUp.pug
  styles/global.css
Labels: enhancement, front, markup

#21 [Feature/blair/signupPage] signupPage javascript 기능 구현
  components/input/input.css
  components/input/input.pug
  pages/signUp/signUp.css
  pages/signUp/signUp.js
  pages/signUp/signUp.pug
  pages/signUp/utils.js
Labels: enhancement, front, javascript, markup

#22 [Feature/dnacu/server] express 기본 설정 및 XMLHttpRequest 모듈화
  .gitignore
  apis/httpRequest.js
  app.js
  package-lock.json
  package.json
  pages/signIn/signIn.js
  pages/signIn/signIn.pug
  routes/complete.js
  routes/index.js
  routes/main.js
  routes/notFound.js
  routes/signIn.js
  routes/signUp.js
  start.sh
Labels: back-end, enhancement

#25 [Feature/dnacu/server] signIn, signUpComplete 페이지 완성
  .gitignore
  data/index.js
  data/userList.db
  pages/signIn/signIn.js
  pages/signUpComplete/signUpComplete.js
  pages/signUpComplete/signUpComplete.pug
  routes/complete.js
  routes/signIn.js
Labels: back-end, enhancement

#26 [Feature/blair/server] signup page 페이지 완성
  .gitignore
  apis/httpRequest.js
  data/index.js
  pages/signUp/signUp.js
  pages/signUp/signUp.pug
  routes/index.js
  routes/signUp.js
Labels: enhancement, front, javascript

#28 [Feature/blair/deploy]
  pages/signUp/signUp.css
  pages/signUp/signUp.js
  pages/signUp/signUp.pug
  routes/signUp.js
Labels: enhancement, front, javascript

#29 [Feature/dnacu/password] bcrypt & session
  apis/httpRequest.js
  app.js
  package-lock.json
  package.json
  pages/main/main.css
  pages/main/main.js
  pages/main/main.pug
  pages/signIn/signIn.css
  pages/signIn/signIn.js
  pages/signIn/signIn.pug
  pages/signUp/signUp.js
  pages/signUpComplete/signUpComplete.css
  public/js/httpRequest.js
  public/js/main.js
  public/js/signIn.js
  public/js/signUp.js
  routes/index.js
  routes/main.js
  routes/signIn.js
  routes/signOut.js
  routes/signUp.js
Labels: back-end, enhancement

#30 [frontend - 가입페이지 markup, javascript 기능 수정]
  data/index.js
  pages/signIn/signIn.css
  pages/signUp/address.js
  pages/signUp/signUp.css
  pages/signUp/signUp.js
  pages/signUp/signUp.pug
  pages/signUpComplete/signUpComplete.css
  pages/signUpComplete/signUpComplete.pug
  public/js/address.js
  public/js/signUp.js
  public/js/signUpComplete.js
Labels: enhancement, front, javascript, markup
